class AddColumnsToVoters < ActiveRecord::Migration[5.2]
  def change
    add_column :voters, :lVoterUniqueID, :integer
    add_column :voters, :sAffNumber, :integer
    add_column :voters, :szStateVoterID, :integer
    add_column :voters, :sVoterTitle, :string
    add_column :voters, :szNameLast, :string
    add_column :voters, :szNameFirst, :string
    add_column :voters, :szNameMiddle, :string
    add_column :voters, :sNameSuffix, :string
    add_column :voters, :sGender, :string
    add_column :voters, :szSitusAddress, :string
    add_column :voters, :szSitusCity, :string
    add_column :voters, :sSitusState, :string
    add_column :voters, :sSitusZip, :integer
    add_column :voters, :sHouseNum, :integer
    add_column :voters, :sUnitAbbr, :string
    add_column :voters, :sUnitNum, :integer
    add_column :voters, :szStreetName, :string
    add_column :voters, :sStreetSuffix, :string
    add_column :voters, :sPreDir, :string
    add_column :voters, :sPostDir, :string
    add_column :voters, :szMailAddress1, :string
    add_column :voters, :szMailAddress2, :string
    add_column :voters, :szMailAddress3, :string
    add_column :voters, :szMailAddress4, :string
    add_column :voters, :szMailZip, :integer
    add_column :voters, :szPhone, :string
    add_column :voters, :szEmailAddress, :string
    add_column :voters, :dtBirthDate, :string
    add_column :voters, :sBirthPlace, :string
    add_column :voters, :dtRegDate, :string
    add_column :voters, :dtOrigRegDate, :string
    add_column :voters, :dtLastUpdate_dt, :string
    add_column :voters, :sStatusCode, :integer
    add_column :voters, :szStatusReasonDesc, :string
    add_column :voters, :sUserCode1, :integer
    add_column :voters, :sUserCode2, :integer
    add_column :voters, :iDuplicateIDFlag, :string
    add_column :voters, :szLanguageName, :string
    add_column :voters, :szPartyName, :string
    add_column :voters, :szAVStatusAbbr, :string
    add_column :voters, :szAVStatusDesc, :string
    add_column :voters, :szPrecinctName, :string
    add_column :voters, :sPrecinctID, :string
    add_column :voters, :sPrecinctPortion, :string
    add_column :voters, :sDistrictID_0, :string
    add_column :voters, :iSubDistrict_0, :string
    add_column :voters, :szDistrictName_0, :string
    add_column :voters, :sDistrictID_1, :string
    add_column :voters, :iSubDistrict_1, :string
    add_column :voters, :szDistrictName_1, :string
    add_column :voters, :sDistrictID_2, :string
    add_column :voters, :iSubDistrict_2, :string
    add_column :voters, :szDistrictName_2, :string
    add_column :voters, :sDistrict_3, :string
    add_column :voters, :iSubDistrict_3, :string
    add_column :voters, :szDistrictName_3, :string
    add_column :voters, :sDistrictID_4, :string
    add_column :voters, :iSubDistrict4, :string
    add_column :voters, :szDistrictName_4, :string
    add_column :voters, :sDistrictID_5, :string
    add_column :voters, :iSubDistrict_5, :string
    add_column :voters, :szDistrictName_5, :string
  end
end
