version: "3"
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: rails-app
      dockerfile: ops/dev/Dockerfile
    image: rails-app
    command: ./script/start
    volumes:
      - box:/box
      - ./rails-app:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  react:
    build:
      context: react-app
      dockerfile: ops/dev/Dockerfile
    image: react-app
    ports:
      - "3001:3000"
    volumes:
      - /app/node_modules
      - ./react-app:/app
    depends_on:
      - web



volumes:
  postgres:
  box:
