# config/app.yml for rails-settings-cached
defaults: &defaults
  precinct_id: [68315]
  canvasser_password: "password"
  note: ""

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
