imageTag: "1.7.6"
cpuRequest: 200m
memoryRequest: 40Mi
cpuLimit: 400m
memoryLimit: 100Mi
ssl:
  enabled: true
  enforced: true
acme:
  enabled: true
  challengeType: http-01
  email: admin@campaignify.net
  staging: false
  logging: true
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
gzip:
  enabled: false # disabled because https://stackoverflow.com/q/46974702/61018
accessLogs:
  enabled: true
dashboard:
  enabled: false
  domain: traefik.campaignify.net
sendAnonymousUsage: true
rbac:
  enabled: true
kubernetes:
  namespaces:
    - default
    - kube-system
    - campaignify-staging
    - campaignify-prod
