module Types
  class VoterType < BaseObject
    graphql_name 'Voter'

    field :id, ID, null: false
    field :lVoterUniqueID, String, null: true, hash_key: "lVoterUniqueID"
    field :sAffNumber, String, null: true, hash_key: "sAffNumber"
    field :szStateVoterID, String, null: true, hash_key: "szStateVoterID"
    field :sVoterTitle, String, null: true, hash_key: "sVoterTitle"
    field :szNameLast, String, null: true, hash_key: "szNameLast"
    field :szNameFirst, String, null: true, hash_key: "szNameFirst"
    field :szNameMiddle, String, null: true, hash_key: "szNameMiddle"
    field :sNameSuffix, String, null: true, hash_key: "sNameSuffix"
    field :sGender, String, null: true, hash_key: "sGender"
    field :szSitusAddress, String, null: true, hash_key: "szSitusAddress"
    field :szSitusCity, String, null: true, hash_key: "szSitusCity"
    field :sSitusState, String, null: true, hash_key: "sSitusState"
    field :sSitusZip, String, null: true, hash_key: "sSitusZip"
    field :sHouseNum, String, null: true, hash_key: "sHouseNum"
    field :sUnitAbbr, String, null: true, hash_key: "sUnitAbbr"
    field :sUnitNum, String, null: true, hash_key: "sUnitNum"
    field :szStreetName, String, null: true, hash_key: "szStreetName"
    field :sStreetSuffix, String, null: true, hash_key: "sStreetSuffix"
    field :sPreDir, String, null: true, hash_key: "sPreDir"
    field :sPostDir, String, null: true, hash_key: "sPostDir"
    field :szMailAddress1, String, null: true, hash_key: "szMailAddress1"
    field :szMailAddress2, String, null: true, hash_key: "szMailAddress2"
    field :szMailAddress3, String, null: true, hash_key: "szMailAddress3"
    field :szMailAddress4, String, null: true, hash_key: "szMailAddress4"
    field :szMailZip, String, null: true, hash_key: "szMailZip"
    field :szPhone, String, null: true, hash_key: "szPhone"
    field :szEmailAddress, String, null: true, hash_key: "szEmailAddress"
    field :dtBirthDate, String, null: true, hash_key: "dtBirthDate"
    field :sBirthPlace, String, null: true, hash_key: "sBirthPlace"
    field :dtRegDate, String, null: true, hash_key: "dtRegDate"
    field :dtOrigRegDate, String, null: true, hash_key: "dtOrigRegDate"
    field :dtLastUpdate_dt, String, null: true, hash_key: "dtLastUpdate_dt"
    field :sStatusCode, String, null: true, hash_key: "sStatusCode"
    field :szStatusReasonDesc, String, null: true, hash_key: "szStatusReasonDesc"
    field :sUserCode1, String, null: true, hash_key: "sUserCode1"
    field :sUserCode2, String, null: true, hash_key: "sUserCode2"
    field :iDuplicateIDFlag, String, null: true, hash_key: "iDuplicateIDFlag"
    field :szLanguageName, String, null: true, hash_key: "szLanguageName"
    field :szPartyName, String, null: true, hash_key: "szPartyName"
    field :szAVStatusAbbr, String, null: true, hash_key: "szAVStatusAbbr"
    field :szAVStatusDesc, String, null: true, hash_key: "szAVStatusDesc"
    field :szPrecinctName, String, null: true, hash_key: "szPrecinctName"
    field :sPrecinctID, String, null: true, hash_key: "sPrecinctID"
    field :sPrecinctPortion, String, null: true, hash_key: "sPrecinctPortion"
    field :sDistrictID_0, String, null: true, hash_key: "sDistrictID_0"
    field :iSubDistrict_0, String, null: true, hash_key: "iSubDistrict_0"
    field :szDistrictName_0, String, null: true, hash_key: "szDistrictName_0"
    field :sDistrictID_1, String, null: true, hash_key: "sDistrictID_1"
    field :iSubDistrict_1, String, null: true, hash_key: "iSubDistrict_1"
    field :szDistrictName_1, String, null: true, hash_key: "szDistrictName_1"
    field :sDistrictID_2, String, null: true, hash_key: "sDistrictID_2"
    field :iSubDistrict_2, String, null: true, hash_key: "iSubDistrict_2"
    field :szDistrictName_2, String, null: true, hash_key: "szDistrictName_2"
    field :sDistrictID_3, String, null: true, hash_key: "sDistrictID_3"
    field :iSubDistrict_3, String, null: true, hash_key: "iSubDistrict_3"
    field :szDistrictName_3, String, null: true, hash_key: "szDistrictName_3"
    field :sDistrictID_4, String, null: true, hash_key: "sDistrictID_4"
    field :iSubDistrict_4, String, null: true, hash_key: "iSubDistrict_4"
    field :szDistrictName_4, String, null: true, hash_key: "szDistrictName_4"
    field :sDistrictID_5, String, null: true, hash_key: "sDistrictID_5"
    field :iSubDistrict_5, String, null: true, hash_key: "iSubDistrict_5"
    field :szDistrictName_5, String, null: true, hash_key: "szDistrictName_5"
    field :note, String, null: true, hash_key: "note"
  end
end
